dynaconf_include:
  - "*.yml"
  - "*.yaml"
  - "**/*.yml"
  - "**/*.yaml"

default:
  debug: true
  log_format: "<g>{time:%Y-%m-%d %H:%M:%S}</g>\t<lvl>{level}\t{message}</lvl>"

production:
  debug: false
